spring:
  application:
    name: central-security
  datasource:
    url: "jdbc:postgresql://localhost:5432/central_security"
    username: "postgres"
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: admin
      password: admin

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#server:
#  port: 0
