openapi: 3.0.3
info:
  description: products API
  title: products API
  version: 1.0.0
servers:
- url: http://localhost:8080/
paths:
  /api/v1/item:
    post:
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewItemRequest'
        required: true
      responses:
        "201":
          description: Created
      summary: POST api/v1/item
      x-contentType: application/json
      x-accepts: application/json
components:
  schemas:
    NewItemRequest:
      example:
        price: 0
        name: name
        description: description
      properties:
        name:
          type: string
        description:
          type: string
        price:
          format: int64
          type: integer
      type: object

